# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Patrick Shao
email: shao.pat@gmail.com
keywords: "jekyll, github, blog, patrick, shao, patrick shao, resume, personal, website"
description: > # this means to ignore newlines until "baseurl:"
  This is my personal website. I plan to blog about my findings as I explore the world 
  of computer science.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.patrickshao.com" # the base hostname & protocol for your site

###twitter_username: jekyllrb
github_username:  patrickshao
linkedin_username: patrickshao
favicon: "favicon.ico"
google_analytics_key: "UA-67181365-2" 

# Build settings
markdown: kramdown
